# Generated by Django 4.2.17 on 2026-03-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_emailverificationotp_pending_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
