# Generated by Django 4.2.17 on 2026-03-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wound',
            name='is_confirmed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
